# Generated by Django 6.1.1 on 2026-09-24 02:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('item_id', models.UUIDField(db_index=True, verbose_name='ítem')),
                ('solicitante_id', models.UUIDField(db_index=True, verbose_name='solicitante')),
                ('posicion_en_cola', models.PositiveIntegerField(blank=True, help_text='Déjalo vacío para ponerlo al final de la cola.', verbose_name='posición en cola')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CONFIRMADA', 'Confirmada'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['item_id', 'posicion_en_cola'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('item_id', 'posicion_en_cola'), name='reserva_posicion_unica_por_item_activa'), models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVA')), fields=('item_id', 'solicitante_id'), name='reserva_unica_activa_por_solicitante_item')],
            },
        ),
    ]
