# Generated by Django 6.1.1 on 2026-09-24 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('solicitante_id', models.UUIDField(help_text='Referencia al PerfilSolicitante/Cuenta sancionado (contexto Identidad).')),
                ('aplicada_por_id', models.UUIDField(help_text='Referencia al Personal/Encargado que aplicó la sanción (contexto Identidad).')),
                ('prestamo_id', models.UUIDField(blank=True, help_text='Préstamo que originó la sanción, si aplica (contexto Circulación).', null=True)),
                ('tipo', models.CharField(choices=[('OBSERVACION', 'Observación'), ('SUSPENSION_TEMPORAL', 'Suspensión temporal'), ('BANEO', 'Baneo')], max_length=30)),
                ('motivo', models.TextField()),
                ('duracion_dias', models.PositiveIntegerField(blank=True, help_text='Días de suspensión, si el tipo lo requiere.', null=True)),
                ('fecha_inicio', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
