# Generated by Django 6.1.1 on 2026-09-24 07:54

import apps.identidad.models
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ENCARGADO', 'Encargado'), ('SUPERVISOR', 'Supervisor'), ('SOLICITANTE', 'Solicitante')], max_length=20), blank=True, default=list, help_text='Conjunto de roles del sistema.')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'ordering': ['correo'],
            },
            managers=[
                ('objects', apps.identidad.models.CuentaManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSolicitante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ALUMNO', 'Alumno'), ('DOCENTE', 'Docente'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('cui', models.CharField(blank=True, max_length=20)),
                ('acta_version', models.CharField(blank=True, max_length=20, verbose_name='versión del acta')),
                ('acta_fecha_firma', models.DateField(blank=True, null=True, verbose_name='fecha de firma del acta')),
                ('etiqueta', models.CharField(choices=[('NUEVO', 'Nuevo'), ('FRECUENTE', 'Frecuente'), ('SANCIONADO', 'Sancionado'), ('BANEADO', 'Baneado')], default='NUEVO', max_length=20)),
                ('habilitado_institucional', models.BooleanField(default=False)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de solicitante',
                'verbose_name_plural': 'perfiles de solicitantes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
