# Generated by Django 6.1.1 on 2026-09-24 02:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('destinatario_id', models.UUIDField(db_index=True, verbose_name='destinatario')),
                ('tipo', models.CharField(choices=[('RECORDATORIO_VENCIMIENTO', 'Recordatorio de vencimiento'), ('ALERTA_ATRASO', 'Alerta de atraso'), ('DISPONIBILIDAD_RESERVA', 'Disponibilidad de reserva'), ('INVENTARIO_BAJO', 'Inventario bajo'), ('ITEM_DANIADO', 'Ítem dañado')], max_length=40)),
                ('canal', models.CharField(choices=[('CORREO', 'Correo')], default='CORREO', max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('leida', models.BooleanField(default=False, verbose_name='leída')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
