# Generated by Django 6.1.1 on 2026-09-24 11:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('item_id', models.UUIDField(db_index=True)),
                ('solicitante_id', models.UUIDField(db_index=True)),
                ('solicitud_id', models.UUIDField(db_index=True)),
                ('encargado_entrega_id', models.UUIDField(db_index=True)),
                ('encargado_devolucion_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('garantia_tipo', models.CharField(choices=[('DNI', 'DNI'), ('CARNE_UNIVERSITARIO', 'Carné universitario'), ('OTRO', 'Otro')], max_length=30)),
                ('garantia_detalle', models.TextField(blank=True)),
                ('garantia_devuelta', models.BooleanField(default=False)),
                ('terminos_aceptados', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('DEVUELTO', 'Devuelto'), ('CERRADO_POR_PERDIDA', 'Cerrado por pérdida')], default='ACTIVO', max_length=30)),
                ('renovaciones_realizadas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'préstamos',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('item_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('categoria_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('solicitante_id', models.UUIDField(db_index=True)),
                ('revisado_por_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('aprobado_por_supervisor_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('finalidad', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ESPERA_SUPERVISOR', 'En espera de supervisor'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=30)),
                ('motivo_rechazo', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
            },
        ),
    ]
