# Generated by Django 6.1.1 on 2026-09-24 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_especial', models.BooleanField(default=False, help_text='Los ítems de categorías especiales requieren aprobación de supervisor.', verbose_name='es especial')),
                ('definicion_atributos', models.JSONField(blank=True, default=dict, help_text='Ejemplo: {"autor": {"tipo": "texto", "requerido": true}}', verbose_name='definición de atributos')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('atributos', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('PRESTADO', 'Prestado'), ('MANTENIMIENTO', 'Mantenimiento'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=20)),
                ('motivo_fuera_servicio', models.CharField(blank=True, max_length=255, verbose_name='motivo fuera de servicio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'ítem',
                'verbose_name_plural': 'ítems',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CondicionFisica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('prestamo_id', models.UUIDField(db_index=True, verbose_name='préstamo')),
                ('responsable_id', models.UUIDField(db_index=True, verbose_name='responsable')),
                ('momento', models.CharField(choices=[('ENTREGA', 'Entrega'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('fecha', models.DateField()),
                ('foto', models.CharField(blank=True, help_text='Ruta o URL de la foto.', max_length=500)),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condiciones', to='catalogo.item')),
            ],
            options={
                'verbose_name': 'condición física',
                'verbose_name_plural': 'condiciones físicas',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('prestamo_id', 'momento'), name='condicion_unica_por_prestamo_y_momento')],
            },
        ),
    ]
