# Generated by Django 6.1.1 on 2026-09-24 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPerdida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('prestamo_id', models.UUIDField(help_text='Préstamo asociado a la pérdida/daño (contexto Circulación).')),
                ('solicitante_id', models.UUIDField(help_text='Solicitante responsable del ítem perdido/dañado (contexto Identidad).')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de reposición estimado del ítem.', max_digits=10, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Caso de pérdida',
                'verbose_name_plural': 'Casos de pérdida',
                'ordering': ['-fecha'],
            },
        ),
    ]
