# Generated by Django 6.1.1 on 2026-09-24 03:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ITEMS_MAS_PRESTADOS', 'Ítems más prestados'), ('USUARIOS_MAS_ACTIVOS', 'Usuarios más activos'), ('TASA_DEVOLUCION_A_TIEMPO', 'Tasa de devolución a tiempo'), ('ITEMS_PERDIDOS_DANIADOS', 'Ítems perdidos o dañados'), ('SANCIONES_POR_PERIODO', 'Sanciones por periodo')], max_length=40)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('generado_por_id', models.UUIDField(help_text='Personal (Administrador) que generó el reporte (contexto Identidad).')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-creado_en'],
            },
        ),
    ]
