# Generated by Django 6.1.1 on 2026-09-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
    ]
