# Generated by Django 6.1.1 on 2026-09-24 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaPrestamo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_item', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('ALUMNO', 'Alumno'), ('DOCENTE', 'Docente'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('duracion_maxima', models.PositiveIntegerField()),
                ('max_renovaciones', models.PositiveIntegerField()),
                ('antelacion_reserva', models.PositiveIntegerField()),
                ('limite_simultaneo_global', models.PositiveIntegerField()),
                ('limite_simultaneo_por_tipo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'política de préstamo',
                'verbose_name_plural': 'políticas de préstamo',
                'unique_together': {('tipo_item', 'tipo_usuario')},
            },
        ),
    ]
