# Generated by Django 6.1.1 on 2026-09-24 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actor_id', models.UUIDField(help_text='Personal que realizó la acción (contexto Identidad).')),
                ('accion', models.CharField(choices=[('ENTREGA', 'Entrega'), ('DEVOLUCION', 'Devolución'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('APROBACION', 'Aprobación'), ('RECHAZO', 'Rechazo'), ('SANCION', 'Sanción'), ('ITEM_DANIADO', 'Ítem dañado')], max_length=30)),
                ('entidad', models.CharField(help_text="Nombre de la entidad afectada, ej. 'Prestamo', 'Item', 'Solicitud'.", max_length=100)),
                ('entidad_id', models.UUIDField(help_text='ID de la entidad afectada.')),
                ('motivo', models.TextField(blank=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
